# Generated by Django 2.1.7 on 2019-03-16 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOneToOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_20', models.TextField(blank=True, null=True)),
                ('field_22a', models.TextField(blank=True, null=True)),
                ('field_22c', models.TextField(blank=True, null=True)),
                ('field_30t', models.TextField(blank=True, null=True)),
                ('field_52a', models.TextField(blank=True, null=True)),
                ('field_82a', models.TextField(blank=True, null=True)),
                ('field_87a', models.TextField(blank=True, null=True)),
                ('field_77h', models.TextField(blank=True, null=True)),
                ('field_30v', models.TextField(blank=True, null=True)),
                ('field_36', models.TextField(blank=True, null=True)),
                ('field_32b', models.TextField(blank=True, null=True)),
                ('field_57a', models.TextField(blank=True, null=True)),
                ('field_33b', models.TextField(blank=True, null=True)),
                ('field_53a', models.TextField(blank=True, null=True)),
                ('field_56', models.TextField(blank=True, null=True)),
                ('field_57d', models.TextField(blank=True, null=True)),
                ('field_58a', models.TextField(blank=True, null=True)),
                ('field_24d', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='matched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.ClientOneToOne')),
            ],
        ),
        migrations.CreateModel(
            name='SgOneToOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_20', models.TextField(blank=True, null=True)),
                ('field_22a', models.TextField(blank=True, null=True)),
                ('field_22c', models.TextField(blank=True, null=True)),
                ('field_30t', models.TextField(blank=True, null=True)),
                ('field_52a', models.TextField(blank=True, null=True)),
                ('field_82a', models.TextField(blank=True, null=True)),
                ('field_87a', models.TextField(blank=True, null=True)),
                ('field_77h', models.TextField(blank=True, null=True)),
                ('field_30v', models.TextField(blank=True, null=True)),
                ('field_36', models.TextField(blank=True, null=True)),
                ('field_32b', models.TextField(blank=True, null=True)),
                ('field_57a', models.TextField(blank=True, null=True)),
                ('field_33b', models.TextField(blank=True, null=True)),
                ('field_53a', models.TextField(blank=True, null=True)),
                ('field_56', models.TextField(blank=True, null=True)),
                ('field_57d', models.TextField(blank=True, null=True)),
                ('field_58a', models.TextField(blank=True, null=True)),
                ('field_24d', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='matched',
            name='sg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.SgOneToOne'),
        ),
    ]
