# Generated by Django 2.1.5 on 2019-03-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOneToOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_20', models.TextField(blank=True, db_column=':20', null=True)),
                ('field_22a', models.TextField(blank=True, db_column=':22A', null=True)),
                ('field_22c', models.TextField(blank=True, db_column=':22C', null=True)),
                ('field_30t', models.TextField(blank=True, db_column=':30T', null=True)),
                ('field_52a', models.TextField(blank=True, db_column=':52A', null=True)),
                ('field_82a', models.TextField(blank=True, db_column=':82A', null=True)),
                ('field_87a', models.TextField(blank=True, db_column=':87A', null=True)),
                ('field_77h', models.TextField(blank=True, db_column=':77H', null=True)),
                ('field_30v', models.TextField(blank=True, db_column=':30V', null=True)),
                ('field_36', models.TextField(blank=True, db_column=':36', null=True)),
                ('field_32b', models.TextField(blank=True, db_column=':32B', null=True)),
                ('field_57a', models.TextField(blank=True, db_column=':57A', null=True)),
                ('field_33b', models.TextField(blank=True, db_column=':33B', null=True)),
                ('field_53a', models.TextField(blank=True, db_column=':53A', null=True)),
                ('field_56', models.TextField(blank=True, db_column=':56', null=True)),
                ('field_57d', models.TextField(blank=True, db_column=':57D', null=True)),
                ('field_58a', models.TextField(blank=True, db_column=':58A', null=True)),
                ('field_24d', models.TextField(blank=True, db_column=':24D', null=True)),
            ],
            options={
                'db_table': 'client_one_to_one',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SgOneToOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_20', models.TextField(blank=True, db_column=':20', null=True)),
                ('field_22a', models.TextField(blank=True, db_column=':22A', null=True)),
                ('field_22c', models.TextField(blank=True, db_column=':22C', null=True)),
                ('field_30t', models.TextField(blank=True, db_column=':30T', null=True)),
                ('field_52a', models.TextField(blank=True, db_column=':52A', null=True)),
                ('field_82a', models.TextField(blank=True, db_column=':82A', null=True)),
                ('field_87a', models.TextField(blank=True, db_column=':87A', null=True)),
                ('field_77h', models.TextField(blank=True, db_column=':77H', null=True)),
                ('field_30v', models.TextField(blank=True, db_column=':30V', null=True)),
                ('field_36', models.TextField(blank=True, db_column=':36', null=True)),
                ('field_32b', models.TextField(blank=True, db_column=':32B', null=True)),
                ('field_57a', models.TextField(blank=True, db_column=':57A', null=True)),
                ('field_33b', models.TextField(blank=True, db_column=':33B', null=True)),
                ('field_53a', models.TextField(blank=True, db_column=':53A', null=True)),
                ('field_56', models.TextField(blank=True, db_column=':56', null=True)),
                ('field_57d', models.TextField(blank=True, db_column=':57D', null=True)),
                ('field_58a', models.TextField(blank=True, db_column=':58A', null=True)),
                ('field_24d', models.TextField(blank=True, db_column=':24D', null=True)),
            ],
            options={
                'db_table': 'sg_one_to_one',
                'managed': True,
            },
        ),
    ]
